import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import styled from 'styled-components'
import { GlobalStyle } from '@/styles/globals'

const inter = Inter({ subsets: ['latin'] })

const Main = styled.main`
    width: 100%;
    max-width: 1280px;
    min-height: 100vh;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    background-color: #1E192C;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Dio - Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Main className={`${inter.className}`}>
          <Header />
        </Main>
    </>
  )
}
